

#GPIOS used in the project. Feel free to change in case.
Gpios:
  AIY_indicator:
    - 25
  assistant_indicators:
    - 05
    - 06
  trigger:
    - 17
Trigger:
  #Change the option below to "Voice" or "PushButton" for trigger
  - "Voice"
